controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    Direction = "UP"
    Link.setImage(img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f . . . . . . . 
        . . . f f e e e e f f . . . . . 
        . . f e e e f f e e e f . . . . 
        . . f f f f 2 2 f f f f . . . . 
        . f f e 2 e 2 2 e 2 e f f . . . 
        . f e 2 f 2 f f f 2 f e f . . . 
        . f f f 2 f e e 2 2 f f f . . . 
        . f e 2 f f e e 2 f e e f . . . 
        f f e f f e e e f e e e f f . . 
        f f e e e e e e e e e e f d f . 
        . . f e e e e e e e e f f b f . 
        . . e f f f f f f f f 4 f b f . 
        . . 4 f 2 2 2 2 2 e d d f c f . 
        . . e f f f f f f e e 4 f f . . 
        . . . f f f . . . . . . . . . . 
        `)
})
function ClearLevel () {
    for (let value of sprites.allOfKind(SpriteKind.Enemy)) {
        value.destroy()
    }
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    timer.debounce("action", 150, function () {
        if (Direction == "DOWN") {
            projectile = sprites.createProjectileFromSprite(img`
                ........................
                ........................
                ........................
                ........................
                ........................
                ...........5............
                ...........c............
                ...........c............
                ..........ccc...........
                .........cc1cc..........
                ..........c1c...........
                ..........c1c...........
                ..........c1c...........
                ..........c1c...........
                ..........c1c...........
                ..........c1c...........
                ..........c1c...........
                ..........c1c...........
                ..........c1c...........
                ...........5............
                ...........5............
                ........................
                ........................
                ........................
                `, Link, 0, 50)
        } else if (Direction == "UP") {
            projectile = sprites.createProjectileFromSprite(img`
                ........................
                ........................
                ........................
                ...........5............
                ...........5............
                ..........c1c...........
                ..........c1c...........
                ..........c1c...........
                ..........c1c...........
                ..........c1c...........
                ..........c1c...........
                ..........c1c...........
                ..........c1c...........
                ..........c1c...........
                .........cc1cc..........
                ..........ccc...........
                ...........c............
                ...........c............
                ...........5............
                ........................
                ........................
                ........................
                ........................
                ........................
                `, Link, 0, -50)
        } else if (Direction == "LEFT") {
            projectile = sprites.createProjectileFromSprite(img`
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ..............c.........
                .....ccccccccccc........
                ...551111111111ccc5.....
                .....ccccccccccc........
                ..............c.........
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `, Link, -50, 0)
        } else if (Direction == "RIGHT") {
            projectile = sprites.createProjectileFromSprite(img`
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                .........c..............
                ........ccccccccccc.....
                .....5ccc111111111155...
                ........ccccccccccc.....
                .........c..............
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `, Link, 50, 0)
        }
    })
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    Direction = "LEFT"
    Link.setImage(img`
        ...............ff.......
        .............ff2ffff....
        ............ff2feeeeff..
        ...........ff22feeeeeff.
        ...........feeeeffeeeef.
        ..........fe2222eefffff.
        ..........f2effff222efff
        ..........fffeeeffffffff
        ..........fee44fbe44efef
        ...........feddfb4d4eef.
        ..........c.eeddd4eeef..
        ....ccccccceddee2222f...
        .....dddddcedd44e444f...
        ......ccccc.eeeefffff...
        ..........c...ffffffff..
        ...............ff..fff..
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    Direction = "RIGHT"
    Link.setImage(img`
        .......ff...............
        ....ffff2ff.............
        ..ffeeeef2ff............
        .ffeeeeef22ff...........
        .feeeeffeeeef...........
        .fffffee2222ef..........
        fffe222ffffe2f..........
        ffffffffeeefff..........
        fefe44ebf44eef..........
        .fee4d4bfddef...........
        ..feee4dddee.c..........
        ...f2222eeddeccccccc....
        ...f444e44ddecddddd.....
        ...fffffeeee.ccccc......
        ..ffffffff...c..........
        ..fff..ff...............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `)
})
function CreateLevel () {
    if (Level == 1) {
        tiles.setTilemap(tilemap`level1`)
    } else if (Level == 2) {
        tiles.setCurrentTilemap(tilemap`level3`)
    } else {
    	
    }
    tiles.placeOnRandomTile(Link, assets.tile`myTile1`)
    for (let index = 0; index < 4; index++) {
        Evil_Kitty = sprites.create(img`
            e e e . . . . e e e . . . . 
            c d d c . . c d d c . . . . 
            c b d d f f d d b c . . . . 
            c 3 b d d b d b 3 c . . . . 
            f b 3 d d d d 3 b f . . . . 
            e d d d d d d d d e . . . . 
            e d 2 d d d d 2 d e . b f b 
            f d d 2 d d 2 d d f . f d f 
            f b d d f f d d 2 f . f d f 
            . f 2 2 2 2 2 2 b b f f d f 
            . f b d d d d d d b b d b f 
            . f d d d d d b d d f f f . 
            . f d f f f d f f d f . . . 
            . f f . . f f . . f f . . . 
            `, SpriteKind.Enemy)
        Evil_Kitty.follow(Link, 40)
        tiles.placeOnRandomTile(Evil_Kitty, sprites.builtin.brick)
    }
}
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    Direction = "DOWN"
    Link.setImage(img`
        ......ffff..............
        ....fff22fff............
        ...fff2222fff...........
        ..fffeeeeeefff..........
        ..ffe222222eef..........
        ..fe2ffffff2ef..........
        ..ffffeeeeffff......ccc.
        .ffefbf44fbfeff....cddc.
        .ffefbf44fbfeff...cddc..
        .fee4dddddd4eef.ccddc...
        fdfeeddddd4eeffecddc....
        fbffee4444ee4fddccc.....
        fbf4f222222f1edde.......
        fcf.f222222f44ee........
        .ff.f445544f............
        ....ffffffff............
        .....ff..ff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile2`, function (sprite, location) {
    ClearLevel()
})
let Evil_Kitty: Sprite = null
let projectile: Sprite = null
let Direction = ""
let Link: Sprite = null
let Level = 0
Level = 1
Link = sprites.create(img`
    ........................
    ......ffff..............
    ....fff22fff............
    ...fff2222fff...........
    ..fffeeeeeefff..........
    ..ffe222222eef..........
    ..fe2ffffff2ef..........
    ..ffffeeeeffff..........
    .ffefbf44fbfeff.........
    .fee41fddf14eef.........
    fdfeeddddd4eff..........
    fbffee444edd4e..........
    fbf4f2222edde...........
    fcf.f22cccee............
    .ff.f44cdc4f............
    ....fffddcff............
    .....fddcff.............
    ....cddc................
    ....cdc.................
    ....cc..................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.moveSprite(Link)
scene.cameraFollowSprite(Link)
CreateLevel()
